"""
app.py — User Chat Interface

Single-screen user interface:
  1. Select a domain
  2. Ask a question
  3. Receive an LLM-generated answer grounded in that domain's documents

LLM and retrieval settings are read from the domain's YAML config.
All domain/document management is in app_admin.py.
"""

import gradio as gr
import logging
from typing import List, Tuple
from core.config_manager import ConfigManager
from core.services.document_service import DocumentService

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Service cache — one DocumentService per domain, reused across requests
# ---------------------------------------------------------------------------
_service_cache: dict = {}


def _get_service(domain_id: str) -> DocumentService:
    if domain_id not in _service_cache:
        _service_cache[domain_id] = DocumentService(domain_id)
    return _service_cache[domain_id]


def _get_domain_choices() -> List[str]:
    return ConfigManager().get_all_domain_names()


# ---------------------------------------------------------------------------
# Chat handler
# ---------------------------------------------------------------------------

def chat(
    message: str,
    history: List[Tuple[str, str]],
    domain_id: str,
) -> Tuple[List[Tuple[str, str]], str]:
    """
    Handle a user message.

    Flow:
      query_text
        → DocumentService.query_with_answer()
          → DocumentPipeline.query()          (hybrid retrieval, config-driven)
          → _generate_answer_with_llm()        (LLM from domain config)
        → return answer + formatted sources
    """
    if not message.strip():
        return history, ""

    if not domain_id:
        return history + [(message, "Please select a domain first.")], ""

    try:
        svc = _get_service(domain_id)
        result = svc.query_with_answer(query_text=message)

        answer = result.get("answer", "No answer generated.")
        sources = result.get("sources", [])
        trace = result.get("trace", {})

        # Append source citations
        if sources:
            cited = []
            for s in sources[:3]:
                title = s.get("title") or s.get("doc_id") or "Unknown"
                page = f" (p.{s['page']})" if s.get("page") else ""
                score = s.get("score", 0.0)
                cited.append(f"• **{title}**{page} — relevance: {score:.2f}")
            answer += "\n\n**Sources:**\n" + "\n".join(cited)

        logger.info(
            f"Query answered: domain={domain_id}, "
            f"chunks={trace.get('raw_results_count', 0)}, "
            f"strategy={trace.get('strategy')}"
        )

    except Exception as e:
        logger.exception(f"Query failed: {e}")
        answer = f"Sorry, an error occurred: {e}"

    return history + [(message, answer)], ""


def refresh_domains() -> gr.update:
    return gr.update(choices=_get_domain_choices())


def on_domain_change(domain_id: str) -> str:
    """Return a status line describing the selected domain's config."""
    if not domain_id:
        return ""
    try:
        cfg = ConfigManager().load_domain_config(domain_id)
        llm = cfg.llm
        if llm:
            return (
                f"Domain: **{cfg.name}** | "
                f"LLM: `{llm.provider} / {llm.model_name}` | "
                f"Retrieval: `{', '.join(cfg.retrieval.strategies)}` "
                f"top-{cfg.retrieval.top_k}"
            )
        return f"Domain: **{cfg.name}**"
    except Exception:
        return f"Domain: `{domain_id}`"


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------

def build_user_app() -> gr.Blocks:
    with gr.Blocks(
        title="RAG Assistant",
        theme=gr.themes.Soft(primary_hue="blue", secondary_hue="teal"),
    ) as demo:

        gr.Markdown("# Multi-Domain RAG Assistant")
        gr.Markdown(
            "Select a domain, then ask questions. "
            "Answers are generated by an LLM using only your domain's documents."
        )

        with gr.Row():
            domain_selector = gr.Dropdown(
                choices=_get_domain_choices(),
                label="Domain",
                value=None,
                scale=4,
                interactive=True,
            )
            refresh_btn = gr.Button("🔄 Refresh", scale=1, size="sm")

        domain_info = gr.Markdown("")

        gr.Markdown("---")

        chatbot = gr.Chatbot(
            label="Conversation",
            height=480,
            bubble_full_width=False,
        )

        with gr.Row():
            query_input = gr.Textbox(
                placeholder="Ask a question about this domain...",
                label="",
                lines=2,
                scale=9,
            )
            send_btn = gr.Button("Send ▶", variant="primary", scale=1)

        clear_btn = gr.Button("🗑 Clear conversation", size="sm")

        # Wire events
        domain_selector.change(
            fn=on_domain_change,
            inputs=[domain_selector],
            outputs=[domain_info],
        )
        refresh_btn.click(fn=refresh_domains, outputs=[domain_selector])
        send_btn.click(
            fn=chat,
            inputs=[query_input, chatbot, domain_selector],
            outputs=[chatbot, query_input],
        )
        query_input.submit(
            fn=chat,
            inputs=[query_input, chatbot, domain_selector],
            outputs=[chatbot, query_input],
        )
        clear_btn.click(fn=lambda: ([], ""), outputs=[chatbot, query_input])

    return demo


if __name__ == "__main__":
    app = build_user_app()
    app.launch(server_name="127.0.0.1", server_port=7860, show_error=True)
